### ISSUE TITLE
в папке uploads не хватает папок

### ISSUE THREAD

**Issue by megaket4up** [vponomarev/ngcms-core#1]
Собаж. Их нет как в репе, так и в ночных сборках.
/uploads/images/
/uploads/files/
/uploads/dsn/

**Comment by vponomarev** [comment]
GIT не позволяет хранить пустые каталоги в репозиториях. Если есть мысли как обойти это ограничение - буду безумно благодарен.
В ночных сборках исправил.

**Comment by easmik** [comment]
Можно во все разместить index.html

**Comment by vponomarev** [comment]
Решил туда положить пустые .htaccess файлы, самый безобидный вариант.

**Comment by megaket4up** [comment]
забыл про
./uploads/dsn/

**Comment by vponomarev** [comment]
И его добавил.
