### ISSUE TITLE
php 8

### ISSUE THREAD

**Issue by irbees2008** [vponomarev/ngcms-core#112]
`Warning: Undefined variable $_SESSION in /home/www/xn----7sbbawujfno3aqk5b5b7b.url3.ru/engine/core.php on line 164

Warning: Undefined variable $_SESSION in /home/www/xn----7sbbawujfno3aqk5b5b7b.url3.ru/engine/core.php on line 164

Warning: Undefined variable $_SESSION in /home/www/xn----7sbbawujfno3aqk5b5b7b.url3.ru/engine/core.php on line 164

Warning: Undefined variable $_SESSION in /home/www/xn----7sbbawujfno3aqk5b5b7b.url3.ru/engine/core.php on line 164

Warning: Undefined variable $_SESSION in /home/www/xn----7sbbawujfno3aqk5b5b7b.url3.ru/engine/core.php on line 164

Warning: Undefined variable $_SESSION in /home/www/xn----7sbbawujfno3aqk5b5b7b.url3.ru/engine/core.php on line 164

Warning: Undefined variable $_SESSION in /home/www/xn----7sbbawujfno3aqk5b5b7b.url3.ru/engine/core.php on line 164

Warning: Undefined property: urlHandler::$configFileName in /home/www/xn----7sbbawujfno3aqk5b5b7b.url3.ru/engine/includes/classes/uhandler.class.php on line 499`

**Comment by russsiq** [comment]
Вот так сделай:

```php

// Initialize last variables
$confArray = [
    // Pre-defined init values
    'predefined' => [
        'HTTP_REFERER' => isset($_SERVER['HTTP_REFERER']) ? $_SERVER['HTTP_REFERER'] : '',
        'PHP_SELF'     => isset($_SERVER['PHP_SELF']) ? $_SERVER['PHP_SELF'] : '',
        'REQUEST_URI'  => isset($_SERVER['REQUEST_URI']) ? $_SERVER['REQUEST_URI'] : '',
        'config'       => [],
        'catz'         => [],
        'catmap'       => [],
        'is_logged'    => false,
    ],
];

// Load pre-defined variables
foreach ($confArray['predefined'] as $key => $value) {
    if(isset($_SESSION[$key])) {
        unset($_SESSION[$key]);
    }

    unset($_GET[$key], $_POST[$key], $_COOKIE[$key], $_ENV[$key]);

    $$key = $value;
}
```

**Comment by russsiq** [comment]
Вот так сделай в `engine\actions\statistics.php`:

```php

function coreVersionSync()
{
    global $config;
    if (($vms = cacheRetrieveFile('coreversion.dat', 86400)) === false) {
        // $paramList = ['ver' => urlencode(engineVersion), 'type' => urlencode(engineVersionType), 'build' => urlencode(engineVersionBuild), 'uuid' => $config['UUID'], 'pdo' => ((extension_loaded('PDO') && extension_loaded('pdo_mysql') && class_exists('PDO')) ? 'yes' : 'no')];
        // $req = new http_get();
        // $vms = $req->get('http://ngcms.ru/sync/versionInfo.php'.'?'.http_build_query($paramList), 3, 1);
        // cacheStoreFile('coreversion.dat', $vms);
    }

    return $vms;
}
```

**Comment by russsiq** [comment]
Вот так сделай в `engine\admin.php`:

```php
$tVars = [
    'php_self'            => $PHP_SELF,
    'home_title'          => $config['home_title'],
    'newpm'               => $newpm,
    'unapproved'          => $unapproved ?? '',
    'main_admin'          => $main_admin,
    'notify'              => $notify ?? '',
    'datetimepicker_lang' => $datetimepicker_lang,
    'h_active_options'    => (in_array($mod, ['options', 'categories', 'static', 'news', 'images', 'files'])) ? ' class="active"' : '',
    'h_active_system'     => (in_array($mod, ['configuration', 'dbo', 'rewrite', 'cron', 'statistics'])) ? ' class="active"' : '',
    'h_active_userman'    => (in_array($mod, ['users', 'ipban', 'ugroup', 'perm'])) ? ' class="active"' : '',
    'h_active_templates'  => (in_array($mod, ['templates'])) ? ' class="active"' : '',
    'h_active_extras'     => (in_array($mod, ['extras'])) ? ' class="active"' : '',
    'h_active_pm'         => ($mod == 'pm') ? ' class="active"' : '',
    'year'                => date('Y'),
    'unapproved1'         => $unapproved1 ?? '',
    'unapproved2'         => $unapproved2 ?? '',
    'unapproved3'         => $unapproved3 ?? '',
    'unnAppText'          => $unnAppText,
    'unnAppLabel'         => $unnAppLabel,
    'newpmText'           => $newpmText,
    'perm'                => [
        'static'        => checkPermission(['plugin' => '#admin', 'item' => 'static'], null, 'view'),
        'categories'    => checkPermission(['plugin' => '#admin', 'item' => 'categories'], null, 'view'),
        'addnews'       => checkPermission(['plugin' => '#admin', 'item' => 'news'], null, 'add'),
        'editnews'      => (checkPermission(['plugin' => '#admin', 'item' => 'news'], null, 'personal.list') || checkPermission(['plugin' => '#admin', 'item' => 'news'], null, 'other.list')),
        'configuration' => checkPermission(['plugin' => '#admin', 'item' => 'configuration'], null, 'details'),
        'dbo'           => checkPermission(['plugin' => '#admin', 'item' => 'dbo'], null, 'details'),
        'cron'          => checkPermission(['plugin' => '#admin', 'item' => 'cron'], null, 'details'),
        'rewrite'       => checkPermission(['plugin' => '#admin', 'item' => 'rewrite'], null, 'details'),
        'templates'     => checkPermission(['plugin' => '#admin', 'item' => 'templates'], null, 'details'),
        'ipban'         => checkPermission(['plugin' => '#admin', 'item' => 'ipban'], null, 'view'),
        'users'         => checkPermission(['plugin' => '#admin', 'item' => 'users'], null, 'view'),
    ],
];
```

**Comment by russsiq** [comment]
Вот так сделай в `engine\includes\classes\uhandler.class.php`:

```php

class urlHandler
{
    protected $configFileName;
    
    // constructor
    public function __construct($options = [])
    {
```

**Comment by irbees2008** [comment]
А что пулл не отправил

**Comment by irbees2008** [comment]
`Warning: Undefined array key "language" in /home/www/xn----7sbbawujfno3aqk5b5b7b.url3.ru/engine/install.php on line 83
Warning: Undefined array key "action" in /home/www/xn----7sbbawujfno3aqk5b5b7b.url3.ru/engine/install.php on line 121
Warning: Undefined array key "action" in /home/www/xn----7sbbawujfno3aqk5b5b7b.url3.ru/engine/install.php on line 132`
это файл установки

**Comment by irbees2008** [comment]
нет переадресации на установку 
`Warning: Undefined array key "prefix" in /home/www/xn----7sbbawujfno3aqk5b5b7b.url3.ru/engine/core.php on line 192
Warning: Undefined array key "timezone" in /home/www/xn----7sbbawujfno3aqk5b5b7b.url3.ru/engine/core.php on line 196
Warning: Undefined array key "mydomains" in /home/www/xn----7sbbawujfno3aqk5b5b7b.url3.ru/engine/includes/inc/multimaster.php on line 84
Warning: Undefined array key "home_url" in /home/www/xn----7sbbawujfno3aqk5b5b7b.url3.ru/engine/includes/inc/multimaster.php on line 124
Warning: Undefined array key "admin_url" in /home/www/xn----7sbbawujfno3aqk5b5b7b.url3.ru/engine/includes/inc/multimaster.php on line 124
Warning: Undefined array key "avatars_url" in /home/www/xn----7sbbawujfno3aqk5b5b7b.url3.ru/engine/includes/inc/multimaster.php on line 124
Warning: Undefined array key "photos_url" in /home/www/xn----7sbbawujfno3aqk5b5b7b.url3.ru/engine/includes/inc/multimaster.php on line 124
Warning: Undefined array key "images_url" in /home/www/xn----7sbbawujfno3aqk5b5b7b.url3.ru/engine/includes/inc/multimaster.php on line 124
Warning: Undefined array key "files_url" in /home/www/xn----7sbbawujfno3aqk5b5b7b.url3.ru/engine/includes/inc/multimaster.php on line 124
Warning: Undefined array key "avatars_dir" in /home/www/xn----7sbbawujfno3aqk5b5b7b.url3.ru/engine/includes/inc/multimaster.php on line 124
Warning: Undefined array key "photos_dir" in /home/www/xn----7sbbawujfno3aqk5b5b7b.url3.ru/engine/includes/inc/multimaster.php on line 124
Warning: Undefined array key "images_dir" in /home/www/xn----7sbbawujfno3aqk5b5b7b.url3.ru/engine/includes/inc/multimaster.php on line 124
Warning: Undefined array key "files_dir" in /home/www/xn----7sbbawujfno3aqk5b5b7b.url3.ru/engine/includes/inc/multimaster.php on line 124
Warning: Undefined array key "attach_url" in /home/www/xn----7sbbawujfno3aqk5b5b7b.url3.ru/engine/includes/inc/multimaster.php on line 124
Warning: Undefined array key "attach_dir" in /home/www/xn----7sbbawujfno3aqk5b5b7b.url3.ru/engine/includes/inc/multimaster.php on line 124
NGCMS: Engine is not installed yet. Please run installer from /engine/install.php`

**Comment by irbees2008** [comment]
Слетает управление форматом ссылок

**Comment by irbees2008** [comment]
Все также c #113
