### ISSUE TITLE
Задействовать пространство имен `NGCMS` для директории `engine\classes`

### ISSUE THREAD

**Issue by russsiq** [vponomarev/ngcms-core#119]
Понимаю, что эта работа объемная, заденет не только ядро, но и часть плагинов и будет состоять из одного PR, включающих в себя несколько шагов:

1. Удаление встроенного загрузчика https://github.com/vponomarev/ngcms-core/blob/master/engine/core.php#L24
2. Изменения в файле `composer.json`:
    ```json
    "autoload": {
        "psr-4": {
            "NGCMS\\": "engine/classes/",
        }
    },
    ```
3. Изменения и переименования непосредственно в самом каталоге:
    - `NGCoreFunctions.class.php` –> `Bootstrap\CoreFunctions.php`
    - `NGEngine.class.php` –> `Container\Container.php`
    - `NGErrorHandler.class.php` –> `Exceptions\Handler.php`
    - `NGEvents.class.php` –> `Log\Events.php`
    - `NGLegacyDB.class.php` –> `Database\LegacyDB.php`
    - `NGPDO.class.php` –> `Database\PDO\Handler.php`
    - `NGTwigEnvironment.class.php` –> `View\Twig\Environment.php`
    - `NGTwigExtension.class.php` –> `View\Twig\Extension.php`
    - `NGTwigLoader.class.php` –> `View\Twig\Loader.php`
    - `NGUser.class.php` –> `Auth\User.php`

Сам вопрос: сделать данные изменения?

**Comment by irbees2008** [comment]
Ну если займешься сразу и плагинами , чтобы все работало, хотя бы в дефолтной сборке, я не против. Ну и от меня презент будет

**Comment by russsiq** [comment]
Отправил PR #120, «споткнулся» об ошибку [styleci](https://github.styleci.io/analyses/2QEjal). Пока минимальные требования PHP не повысятся до [8.0](https://www.php.net/manual/ru/language.types.declarations.php#language.types.declarations.union) – данная тема не актуальна, к сожалению.

**Comment by megaket4up** [comment]
О, я начинал делать подобное (я правда не помню, на чем остановился  😁), идея хорошая

https://github.com/megaket4up/ngcms-core/tree/namespaces/engine/classes

Еще к этому списку (или на будущее) можно вынести из ядра инициализацию каких-то частей в отдельные части, на пример как это сделано в `Laravel` (`ServiceProvider`)

Как пример (это не совсем то но то 😁) https://github.com/megaket4up/ngcms-core/blob/namespaces/engine/classes/Twig/TwigBootsrap.php 
и в ядре https://github.com/megaket4up/ngcms-core/blob/namespaces/engine/core.php#L267

**Comment by russsiq** [comment]
@megaket4up, собственно из-за плагинов я и начал эту историю. Историю о том, как создавать фреймворко-независимые плагины.

Тут идет портянка про *agnostic*, *psr*, *ddd*, *микро-сервисы*, *tdd*, куча ссылок, переосознание ООП, понимание, что PSR – это не только стиль кодирования и др. термины.

Но все упирается в то, что нет *пространств имен*. Невозможно создавать плагины для NGCMS (фреймворко-независимые пакеты), когда в пакете не можешь создать [`ServiceProvider`](https://github.com/russsiq/laravel-docs-ru/blob/8.x/docs/providers.md) для NGCMS.

https://github.com/russsiq/ddd-in-php

**Comment by russsiq** [comment]
У меня еще был в профиле один перевод: чисто по пакетам для *Laravel*, который – каким бы он не казался на первый взгляд полноценным – при переводе выявил себя как устаревший и с кучей сомнительных практик. Вдобавок к этому, автор перешел к политике поблочного копирования документации *Laravel*.

Нет такой золотой пули (учебного курса), при помощи которой можно было бы единожды создать фреймворко-независимый пакет с кучей поставщиков.

**Comment by russsiq** [comment]
Но это задача не первостепенная, я по образованию не программист: подожду, когда выйдет *PHP 8.Ƭ*, *Laravel v.100+500*, NG 0.9.5.1.

**Comment by russsiq** [comment]
https://www.youtube.com/watch?v=s3Pzu0A5FuM

**Comment by russsiq** [comment]
Покинутый репо создателем https://www.youtube.com/watch?v=dJP7lu9gXjc

На днях сериал поплся [Чудотворцы](https://www.kinopoisk.ru/series/1111018/). Окромя первого сезона смотреть )

**Comment by russsiq** [comment]
Виталий, вы где ?)
