### ISSUE TITLE
Убрать $PHP_SELF

### ISSUE THREAD

**Issue by stdex** [vponomarev/ngcms-core#14]
Во многих местах используется $PHP_SELF, нужно либо избавится от него.
http://stackoverflow.com/questions/14093316/why-use-serverphp-self-instead-of

**Comment by irbees2008** [comment]
В файле engine\includes\inc\functions.inc.php есть функция
Код:

function generateAdminPagelist($param){
В ней нужно заменить


$pages .= " ... ";
на


$pages .= $nav['dots'];
4 раза.
