### ISSUE TITLE
 functions

### ISSUE THREAD

**Issue by irbees2008** [vponomarev/ngcms-core#23]
Добавить в functions для  реализации использования доп. bbcode 
`function insertfortext(teg,val,field){
        try { var    msgfield = document.getElementById((field=='')?'content':field);
        } catch (err) {
            return false;
        }    
        var open ='['+teg+'="'+val+'"]';
        var close='[/'+teg+']';
    // IE support
    if (document.selection && document.selection.createRange){
        msgfield.focus();
        sel = document.selection.createRange();
        sel.text = open + sel.text + close;
        msgfield.focus();
    }
    // Moz support
    else if (msgfield.selectionStart || msgfield.selectionStart == "0"){
        var startPos = msgfield.selectionStart;
        var endPos = msgfield.selectionEnd;
        msgfield.value = msgfield.value.substring(0, startPos) + open + msgfield.value.substring(startPos, endPos) + close + msgfield.value.substring(endPos, msgfield.value.length);
        msgfield.selectionStart = msgfield.selectionEnd = endPos + open.length + close.length;
        msgfield.focus();
    }
    // Fallback support for other browsers
    else {
        msgfield.value += open + close;
        msgfield.focus();
    }
    return true;
	} `

**Comment by stdex** [comment]
Для чего это?

**Comment by irbees2008** [comment]
Добавить выбор размера шрифта, какой шрифт использовать ,цвет фона текста , а то постоянно после обновления восстанавливать надо, и не только у меня
