### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by irbees2008** [vponomarev/ngcms-core#26]
`Warning: require(/home/www/utf.url3.ru/vendor/autoload.php): failed to open stream: No such file or directory in /home/www/utf.url3.ru/engine/core.php on line 21

Fatal error: require(): Failed opening required '/home/www/utf.url3.ru/vendor/autoload.php' (include_path='.:/php/includes:/usr/share/php') in /home/www/utf.url3.ru/engine/core.php on line 21` 
PHP7.0

**Comment by megaket4up** [comment]
Нужно установить зависимости, для этого нужно выполнить `composer install` в папке `/home/www/utf.url3.ru`

**Comment by irbees2008** [comment]
То есть  стандартная установка не работает? И каким образом  это сделать на хостинге?

**Comment by megaket4up** [comment]
Подключится по ssh, скачать `composer.phar` и выполнить `php composer.phar install`

https://getcomposer.org/
https://getcomposer.org/doc/00-intro.md
https://getcomposer.org/doc/00-intro.md#installation-linux-unix-macos

**Comment by irbees2008** [comment]
Короче говоря установки из коробки не получится, уже только это отолкнет тех кто сейчас пользуется системой.

**Comment by stdex** [comment]
Смысл изменения:
1) Чтобы не таскать внури ядра NG сторонние библиотеки (twig, phpmailer, что-то ещё что может понадобиться позже).
2) Начать использовать namespace для классов и подгрузку по psr0.

Если речь о shared хостингах, где нет composer, то стандартное решение - генерировать vendor локально и потом загружать вручную по ftp/sftp.

**Comment by irbees2008** [comment]
Народу  Нужна простота установки, т.е. двиг должен ставится сразу из коробки. Скачал ,залил ,установил. Да  у большинства наверное shared хостинги, Я почитал ,да разберусь с локалкой ,потом залить на хостинг, но  Каждому  разжевывать? С Русиком уже это проходили, как вариант можете посмотреть , он реализовал  из коробки https://github.com/russsiq/bixbite

**Comment by russsiq** [comment]
У меня там тоже папка `vendor` пуста )

Просто я предварительно установил `composer` и `npm` зависимости на локалке. И скидывал тебе вариант подготовленный.

А так да, я думаю, что для рядовых пользователей нужно выпускать версии с подготовленной начинкой.

**Comment by irbees2008** [comment]
О привет, где пропал? Так я вроде скачивал у тебя с гита?

**Comment by russsiq** [comment]
Привет, привет. Нет, нет. Архив я тебе скидывал )

**Comment by irbees2008** [comment]
Да,ну тогда да я не посмотрел.

**Comment by megaket4up** [comment]
Можно будет прикрутить к репе какой-нибудь сервис, чтоб он собирал все это добро (релиз кандидаты, релиз) в архивчик

**Comment by irbees2008** [comment]
Может проще получится , типа  установка стандартная, а из админки уже  все остальное

**Comment by megaket4up** [comment]
Обрати внимание, что RC переведен на UTF-8, а плагины в мастер ветке до сих пор в cp1251

**Comment by irbees2008** [comment]
Это я знаю, и вижу, что кроме конвертации еще и переписывать все надо  , на промежуточных версиях тестировал

**Comment by irbees2008** [comment]
Надо было сначала просто перевести на utf а потом все остальное, что бы мигрировать можно было спокойно.
