### ISSUE TITLE
index.php

### ISSUE THREAD

**Issue by irbees2008** [vponomarev/ngcms-core#35]
https://github.com/vponomarev/ngcms-core/blob/b4a37f4fce73ab59d50e1deea4977980eeecd374/engine/upgrade.php#L37
Файла сейчас нет , сейчас index.tpl

**Comment by megaket4up** [comment]
Я думаю, что сюда нужно создать отдельный шаблон без меню из админки (по аналогии с установщиком)

**Comment by irbees2008** [comment]
было бы не плохо,
