### ISSUE TITLE
twig-3x

### ISSUE THREAD

**Issue by megaket4up** [vponomarev/ngcms-core#54]
> И если на то пошло, то, возможно, есть смысл переключиться на ветку 3.0 (предварительно пофиксив при необходимости кастомный loader).

Они немножко поменяли все в 3 ветке твига и чтоб на нее переключится нужно будет поменять вызовы некоторых функций по всему двигу и плагинам, либо написать обертку. И еще я не разобрался как прокинуть глобальные переменные по ссылке правильно. 

Двиг падал на функции loadTemplate, у которой поменяли колво аргументов. Обертку написал. 
https://github.com/megaket4up/ngcms-core/tree/twig-3.x

_Originally posted by @vponomarev in https://github.com/vponomarev/ngcms-core/pull/52_

**Comment by vponomarev** [comment]
> Двиг падал на функции loadTemplate, у которой поменяли колво аргументов. Обертку написал.

А где лежит обёртка?
Если работает, то сделай, plz, pull request с патчами.

**Comment by megaket4up** [comment]
pr #57

**Comment by megaket4up** [comment]
https://github.com/megaket4up/ngcms-core/blob/f6074f27e0a81c2e177e4870222ce6396b5c995c/engine/classes/NGTwigEnvironment.class.php#L24
