### ISSUE TITLE
Формирование приставки `Re:` в модуле личных сообщений 

### ISSUE THREAD

**Issue by russsiq** [vponomarev/ngcms-core#76]
В модуле личных сообщений при написании письма/ответа в Заголовок подставляется приставка `Re:`, которая увеличивает количество символов в поле `title`. И, если до этого Заголовок имел длину в 50 разрешенных символов, то при написании ответа, естественно, выводится сообщение о превышении длины Заголовка:

> Заголовок не должен быть пустым или превышать 50 символов!

Нужно рассмотреть вариант с автоматической подстановкой этого префикса (`Re:`), чтобы он не заносился в БД.

**Comment by vponomarev** [comment]
Исправлю.
Можешь для read.tpl тоже поправить оформление?
Там явно не input нужен уже.

**Comment by vponomarev** [comment]
Исправил.
