### ISSUE TITLE
Установка

### ISSUE THREAD

**Issue by irbees2008** [vponomarev/ngcms-core#98]
При установке, на ступени когда задается логин и пароль, название сайта , если поля оставить пустые то идет дальнейшая установка. Так не должно быть, в админку потом не попадешь,надо заново устанавливать или в базу ручками прописывать админа

**Comment by vponomarev** [comment]
Исправил, https://github.com/vponomarev/ngcms-core/commit/7ba7b7bf8437a4872f9d6c20078bfb3bf41e6dbc
